#The information contained in this file and the corresponding presentation is not finanicial advice and should not be misconstrued or interpreted as such.
#This file is for example puposes only and should not be used to make financial decsisions. This file is to be used at the users own risk.

#  You would need to add Holiday days when the market it is closed to more appropriately model this data

#Installing Packages
#install.packages("quantmod", dependencies=TRUE)
#install.packages("xts", dependencies=TRUE)
#install.packages("forecast", dependencies=TRUE)
#install.packages("ggplot2", dependencies=TRUE)
#install.packages("sqldf", dependencies=TRUE)
#install.packages("reshape", dependencies=TRUE)
#install.packages("zoo", dependencies=TRUE)
#install.packages("stringr", dependencies=TRUE)

#Loading packages
library("quantmod")
library("xts")
library("forecast")
library("ggplot2")
library("sqldf")
library("reshape")
library("zoo")
library("stringr")

Stocks<-data.frame(Stocks=c("AXP", "BA", "CAT", "CSCO", "CVX", "DD", "DIS", "GE", "GS", "HD", "IBM", "INTC", "JNJ", "JPM", "KO", "MCD", "MMM", "MRK", "MSFT", "NKE", "PFE", "PG", "T", "TRV", "UNH", "UTX", "V", "VZ", "WMT", "XOM"))

# Downloading data from Yahoo
# Note that data more than 200 days in the past is not officially supported but it still works
getSymbols("AXP", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("BA", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("CAT", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("CSCO", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("CVX", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("DD", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("DIS", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("GE", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("GS", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("HD", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("IBM", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("INTC", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("JNJ", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("JPM", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("KO", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("MCD", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("MMM", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("MRK", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2012-12-31", src="yahoo")
getSymbols("MSFT", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("NKE", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("PFE", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("PG", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("T", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("TRV", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("UNH", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("UTX", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("V", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("VZ", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("WMT", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")
getSymbols("XOM", reload.Symols=TRUE, verbose=TRUE, warnings=TRUE, from="2013-01-07", src="yahoo")


#Covert the xts data to a dataframe and keep the date
AXP<-data.frame(Date=index(AXP), coredata(AXP))
BA<-data.frame(Date=index(BA), coredata(BA))
CAT<-data.frame(Date=index(CAT), coredata(CAT))
CSCO<-data.frame(Date=index(CSCO), coredata(CSCO))
CVX<-data.frame(Date=index(CVX), coredata(CVX))
DD<-data.frame(Date=index(DD), coredata(DD))
DIS<-data.frame(Date=index(DIS), coredata(DIS))
GE<-data.frame(Date=index(GE), coredata(GE))
GS<-data.frame(Date=index(GS), coredata(GS))
HD<-data.frame(Date=index(HD), coredata(HD))
IBM<-data.frame(Date=index(IBM), coredata(IBM))
INTC<-data.frame(Date=index(INTC), coredata(INTC))
JNJ<-data.frame(Date=index(JNJ), coredata(JNJ))
JPM<-data.frame(Date=index(JPM), coredata(JPM))
KO<-data.frame(Date=index(KO), coredata(KO))
MCD<-data.frame(Date=index(MCD), coredata(MCD))
MMM<-data.frame(Date=index(MMM), coredata(MMM))
MRK<-data.frame(Date=index(MRK), coredata(MRK))
MSFT<-data.frame(Date=index(MSFT), coredata(MSFT))
NKE<-data.frame(Date=index(NKE), coredata(NKE))
PFE<-data.frame(Date=index(PFE), coredata(PFE))
PG<-data.frame(Date=index(PG), coredata(PG))
T<-data.frame(Date=index(T), coredata(T))
TRV<-data.frame(Date=index(TRV), coredata(TRV))
UNH<-data.frame(Date=index(UNH), coredata(UNH))
UTX<-data.frame(Date=index(UTX), coredata(UTX))
V<-data.frame(Date=index(V), coredata(V))
VZ<-data.frame(Date=index(VZ), coredata(VZ))
WMT<-data.frame(Date=index(WMT), coredata(WMT))
XOM<-data.frame(Date=index(XOM), coredata(XOM))

# Convert from a dataframe to a time series (TS) object
AXP_TS<-ts(AXP$AXP.Close, start=c(2013,01,07),frequency=5)
BA_TS<-ts(BA$BA.Close, start=c(2013,01,07),frequency=5)
CAT_TS<-ts(CAT$CAT.Close, start=c(2013,01,07),frequency=5)
CSCO_TS<-ts(CSCO$CSCO.Close, start=c(2013,01,07),frequency=5)
CVX_TS<-ts(CVX$CVX.Close, start=c(2013,01,07),frequency=5)
DD_TS<-ts(DD$DD.Close, start=c(2013,01,07),frequency=5)
DIS_TS<-ts(DIS$DIS.Close, start=c(2013,01,07),frequency=5)
GE_TS<-ts(GE$GE.Close, start=c(2013,01,07),frequency=5)
GS_TS<-ts(GS$GS.Close, start=c(2013,01,07),frequency=5)
HD_TS<-ts(HD$HD.Close, start=c(2013,01,07),frequency=5)
IBM_TS<-ts(IBM$IBM.Close, start=c(2013,01,07),frequency=5)
INTC_TS<-ts(INTC$INTC.Close, start=c(2013,01,07),frequency=5)
JNJ_TS<-ts(JNJ$JNJ.Close, start=c(2013,01,07),frequency=5)
JPM_TS<-ts(JPM$JPM.Close, start=c(2013,01,07),frequency=5)
KO_TS<-ts(KO$KO.Close, start=c(2013,01,07),frequency=5)
MCD_TS<-ts(MCD$MCD.Close, start=c(2013,01,07),frequency=5)
MMM_TS<-ts(MMM$MMM.Close, start=c(2013,01,07),frequency=5)
MRK_TS<-ts(MRK$MRK.Close, start=c(2013,01,07),frequency=5)
MSFT_TS<-ts(MSFT$MSFT.Close, start=c(2013,01,07),frequency=5)
NKE_TS<-ts(NKE$NKE.Close, start=c(2013,01,07),frequency=5)
PFE_TS<-ts(PFE$PFE.Close, start=c(2013,01,07),frequency=5)
PG_TS<-ts(PG$PG.Close, start=c(2013,01,07),frequency=5)
T_TS<-ts(T$T.Close, start=c(2013,01,07),frequency=5)
TRV_TS<-ts(TRV$TRV.Close, start=c(2013,01,07),frequency=5)
UNH_TS<-ts(UNH$UNH.Close, start=c(2013,01,07),frequency=5)
UTX_TS<-ts(UTX$UTX.Close, start=c(2013,01,07),frequency=5)
V_TS<-ts(V$V.Close, start=c(2013,01,07),frequency=5)
VZ_TS<-ts(VZ$VZ.Close, start=c(2013,01,07),frequency=5)
WMT_TS<-ts(WMT$WMT.Close, start=c(2013,01,07),frequency=5)
XOM_TS<-ts(XOM$XOM.Close, start=c(2013,01,07),frequency=5)

#Produce Forecasts
AXP_Fcst<-auto.arima(AXP_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
BA_Fcst<-auto.arima(BA_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
CAT_Fcst<-auto.arima(CAT_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
CSCO_Fcst<-auto.arima(CSCO_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
CVX_Fcst<-auto.arima(CVX_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
DD_Fcst<-auto.arima(DD_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
DIS_Fcst<-auto.arima(DIS_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
GE_Fcst<-auto.arima(GE_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
GS_Fcst<-auto.arima(GS_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
HD_Fcst<-auto.arima(HD_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
IBM_Fcst<-auto.arima(IBM_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
INTC_Fcst<-auto.arima(INTC_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
JNJ_Fcst<-auto.arima(JNJ_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
JPM_Fcst<-auto.arima(JPM_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
KO_Fcst<-auto.arima(KO_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
MCD_Fcst<-auto.arima(MCD_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
MMM_Fcst<-auto.arima(MMM_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
MRK_Fcst<-auto.arima(MRK_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
MSFT_Fcst<-auto.arima(MSFT_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
NKE_Fcst<-auto.arima(NKE_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
PFE_Fcst<-auto.arima(PFE_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
PG_Fcst<-auto.arima(PG_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
T_Fcst<-auto.arima(T_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
TRV_Fcst<-auto.arima(TRV_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
UNH_Fcst<-auto.arima(UNH_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
UTX_Fcst<-auto.arima(UTX_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
V_Fcst<-auto.arima(V_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
VZ_Fcst<-auto.arima(VZ_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
WMT_Fcst<-auto.arima(WMT_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)
XOM_Fcst<-auto.arima(XOM_TS, seasonal=TRUE, allowdrift=TRUE, stepwise=FALSE)

#Convert the ARIMA display to matrix form
AXP_m<-as.matrix(AXP_Fcst$arma)
BA_m<-as.matrix(BA_Fcst$arma)
CAT_m<-as.matrix(CAT_Fcst$arma)
CSCO_m<-as.matrix(CSCO_Fcst$arma)
CVX_m<-as.matrix(CVX_Fcst$arma)
DD_m<-as.matrix(DD_Fcst$arma)
DIS_m<-as.matrix(DIS_Fcst$arma)
GE_m<-as.matrix(GE_Fcst$arma)
GS_m<-as.matrix(GS_Fcst$arma)
HD_m<-as.matrix(HD_Fcst$arma)
IBM_m<-as.matrix(IBM_Fcst$arma)
INTC_m<-as.matrix(INTC_Fcst$arma)
JNJ_m<-as.matrix(JNJ_Fcst$arma)
JPM_m<-as.matrix(JPM_Fcst$arma)
KO_m<-as.matrix(KO_Fcst$arma)
MCD_m<-as.matrix(MCD_Fcst$arma)
MMM_m<-as.matrix(MMM_Fcst$arma)
MRK_m<-as.matrix(MRK_Fcst$arma)
MSFT_m<-as.matrix(MSFT_Fcst$arma)
NKE_m<-as.matrix(NKE_Fcst$arma)
PFE_m<-as.matrix(PFE_Fcst$arma)
PG_m<-as.matrix(PG_Fcst$arma)
T_m<-as.matrix(T_Fcst$arma)
TRV_m<-as.matrix(TRV_Fcst$arma)
UNH_m<-as.matrix(UNH_Fcst$arma)
UTX_m<-as.matrix(UTX_Fcst$arma)
V_m<-as.matrix(V_Fcst$arma)
VZ_m<-as.matrix(VZ_Fcst$arma)
WMT_m<-as.matrix(WMT_Fcst$arma)
XOM_m<-as.matrix(XOM_Fcst$arma)


#Make a strin specifying the ARIMA model for the excel file output
AXP_m<-str_c(as.character(class(AXP_Fcst)),as.character("("), AXP_m[1,], AXP_m[6,], AXP_m[2], as.character(")"), as.character("("), AXP_m[3,], AXP_m[7,], AXP_m[4], as.character(")"))
BA_m<-str_c(as.character(class(BA_Fcst)),as.character("("), BA_m[1,], BA_m[6,], BA_m[2], as.character(")"), as.character("("), BA_m[3,], BA_m[7,], BA_m[4], as.character(")"))
CAT_m<-str_c(as.character(class(CAT_Fcst)),as.character("("), CAT_m[1,], CAT_m[6,], CAT_m[2], as.character(")"), as.character("("), CAT_m[3,], CAT_m[7,], CAT_m[4], as.character(")"))
CSCO_m<-str_c(as.character(class(CSCO_Fcst)),as.character("("), CSCO_m[1,], CSCO_m[6,], CSCO_m[2], as.character(")"), as.character("("), CSCO_m[3,], CSCO_m[7,], CSCO_m[4], as.character(")"))
CVX_m<-str_c(as.character(class(CVX_Fcst)),as.character("("), CVX_m[1,], CVX_m[6,], CVX_m[2], as.character(")"), as.character("("), CVX_m[3,], CVX_m[7,], CVX_m[4], as.character(")"))
DD_m<-str_c(as.character(class(DD_Fcst)),as.character("("), DD_m[1,], DD_m[6,], DD_m[2], as.character(")"), as.character("("), DD_m[3,], DD_m[7,], DD_m[4], as.character(")"))
DIS_m<-str_c(as.character(class(DIS_Fcst)),as.character("("), DIS_m[1,], DIS_m[6,], DIS_m[2], as.character(")"), as.character("("), DIS_m[3,], DIS_m[7,], DIS_m[4], as.character(")"))
GE_m<-str_c(as.character(class(GE_Fcst)),as.character("("), GE_m[1,], GE_m[6,], GE_m[2], as.character(")"), as.character("("), GE_m[3,], GE_m[7,], GE_m[4], as.character(")"))
GS_m<-str_c(as.character(class(GS_Fcst)),as.character("("), GS_m[1,], GS_m[6,], GS_m[2], as.character(")"), as.character("("), GS_m[3,], GS_m[7,], GS_m[4], as.character(")"))
HD_m<-str_c(as.character(class(HD_Fcst)),as.character("("), HD_m[1,], HD_m[6,], HD_m[2], as.character(")"), as.character("("), HD_m[3,], HD_m[7,], HD_m[4], as.character(")"))
IBM_m<-str_c(as.character(class(IBM_Fcst)),as.character("("), IBM_m[1,], IBM_m[6,], IBM_m[2], as.character(")"), as.character("("), IBM_m[3,], IBM_m[7,], IBM_m[4], as.character(")"))
INTC_m<-str_c(as.character(class(INTC_Fcst)),as.character("("), INTC_m[1,], INTC_m[6,], INTC_m[2], as.character(")"), as.character("("), INTC_m[3,], INTC_m[7,], INTC_m[4], as.character(")"))
JNJ_m<-str_c(as.character(class(JNJ_Fcst)),as.character("("), JNJ_m[1,], JNJ_m[6,], JNJ_m[2], as.character(")"), as.character("("), JNJ_m[3,], JNJ_m[7,], JNJ_m[4], as.character(")"))
JPM_m<-str_c(as.character(class(JPM_Fcst)),as.character("("), JPM_m[1,], JPM_m[6,], JPM_m[2], as.character(")"), as.character("("), JPM_m[3,], JPM_m[7,], JPM_m[4], as.character(")"))
KO_m<-str_c(as.character(class(KO_Fcst)),as.character("("), KO_m[1,], KO_m[6,], KO_m[2], as.character(")"), as.character("("), KO_m[3,], KO_m[7,], KO_m[4], as.character(")"))
MCD_m<-str_c(as.character(class(MCD_Fcst)),as.character("("), MCD_m[1,], MCD_m[6,], MCD_m[2], as.character(")"), as.character("("), MCD_m[3,], MCD_m[7,], MCD_m[4], as.character(")"))
MMM_m<-str_c(as.character(class(MMM_Fcst)),as.character("("), MMM_m[1,], MMM_m[6,], MMM_m[2], as.character(")"), as.character("("), MMM_m[3,], MMM_m[7,], MMM_m[4], as.character(")"))
MRK_m<-str_c(as.character(class(MRK_Fcst)),as.character("("), MRK_m[1,], MRK_m[6,], MRK_m[2], as.character(")"), as.character("("), MRK_m[3,], MRK_m[7,], MRK_m[4], as.character(")"))
MSFT_m<-str_c(as.character(class(MSFT_Fcst)),as.character("("), MSFT_m[1,], MSFT_m[6,], MSFT_m[2], as.character(")"), as.character("("), MSFT_m[3,], MSFT_m[7,], MSFT_m[4], as.character(")"))
NKE_m<-str_c(as.character(class(NKE_Fcst)),as.character("("), NKE_m[1,], NKE_m[6,], NKE_m[2], as.character(")"), as.character("("), NKE_m[3,], NKE_m[7,], NKE_m[4], as.character(")"))
PFE_m<-str_c(as.character(class(PFE_Fcst)),as.character("("), PFE_m[1,], PFE_m[6,], PFE_m[2], as.character(")"), as.character("("), PFE_m[3,], PFE_m[7,], PFE_m[4], as.character(")"))
PG_m<-str_c(as.character(class(PG_Fcst)),as.character("("), PG_m[1,], PG_m[6,], PG_m[2], as.character(")"), as.character("("), PG_m[3,], PG_m[7,], PG_m[4], as.character(")"))
T_m<-str_c(as.character(class(T_Fcst)),as.character("("), T_m[1,], T_m[6,], T_m[2], as.character(")"), as.character("("), T_m[3,], T_m[7,], T_m[4], as.character(")"))
TRV_m<-str_c(as.character(class(TRV_Fcst)),as.character("("), TRV_m[1,], TRV_m[6,], TRV_m[2], as.character(")"), as.character("("), TRV_m[3,], TRV_m[7,], TRV_m[4], as.character(")"))
UNH_m<-str_c(as.character(class(UNH_Fcst)),as.character("("), UNH_m[1,], UNH_m[6,], UNH_m[2], as.character(")"), as.character("("), UNH_m[3,], UNH_m[7,], UNH_m[4], as.character(")"))
UTX_m<-str_c(as.character(class(UTX_Fcst)),as.character("("), UTX_m[1,], UTX_m[6,], UTX_m[2], as.character(")"), as.character("("), UTX_m[3,], UTX_m[7,], UTX_m[4], as.character(")"))
V_m<-str_c(as.character(class(V_Fcst)),as.character("("), V_m[1,], V_m[6,], V_m[2], as.character(")"), as.character("("), V_m[3,], V_m[7,], V_m[4], as.character(")"))
VZ_m<-str_c(as.character(class(VZ_Fcst)),as.character("("), VZ_m[1,], VZ_m[6,], VZ_m[2], as.character(")"), as.character("("), VZ_m[3,], VZ_m[7,], VZ_m[4], as.character(")"))
WMT_m<-str_c(as.character(class(WMT_Fcst)),as.character("("), WMT_m[1,], WMT_m[6,], WMT_m[2], as.character(")"), as.character("("), WMT_m[3,], WMT_m[7,], WMT_m[4], as.character(")"))
XOM_m<-str_c(as.character(class(XOM_Fcst)),as.character("("), XOM_m[1,], XOM_m[6,], XOM_m[2], as.character(")"), as.character("("), XOM_m[3,], XOM_m[7,], XOM_m[4], as.character(")"))

#Create 
ARIMA<-data.frame(ARIMA=c(AXP_m, BA_m, CAT_m, CSCO_m, CVX_m, DD_m, DIS_m, GE_m, GS_m, HD_m, IBM_m, INTC_m, JNJ_m, JPM_m, KO_m, MCD_m, MMM_m, MRK_m, MSFT_m, NKE_m, PFE_m, PG_m, T_m, TRV_m, UNH_m, UTX_m, V_m, VZ_m, WMT_m, XOM_m))

#Forecast the Data for the next 5 days
AXP_Fcst<-data.frame(forecast(AXP_Fcst, h=5))
BA_Fcst<-data.frame(forecast(BA_Fcst, h=5))
CAT_Fcst<-data.frame(forecast(CAT_Fcst, h=5))
CSCO_Fcst<-data.frame(forecast(CSCO_Fcst, h=5))
CVX_Fcst<-data.frame(forecast(CVX_Fcst, h=5))
DD_Fcst<-data.frame(forecast(DD_Fcst, h=5))
DIS_Fcst<-data.frame(forecast(DIS_Fcst, h=5))
GE_Fcst<-data.frame(forecast(GE_Fcst, h=5))
GS_Fcst<-data.frame(forecast(GS_Fcst, h=5))
HD_Fcst<-data.frame(forecast(HD_Fcst, h=5))
IBM_Fcst<-data.frame(forecast(IBM_Fcst, h=5))
INTC_Fcst<-data.frame(forecast(INTC_Fcst, h=5))
JNJ_Fcst<-data.frame(forecast(JNJ_Fcst, h=5))
JPM_Fcst<-data.frame(forecast(JPM_Fcst, h=5))
KO_Fcst<-data.frame(forecast(KO_Fcst, h=5))
MCD_Fcst<-data.frame(forecast(MCD_Fcst, h=5))
MMM_Fcst<-data.frame(forecast(MMM_Fcst, h=5))
MRK_Fcst<-data.frame(forecast(MRK_Fcst, h=5))
MSFT_Fcst<-data.frame(forecast(MSFT_Fcst, h=5))
NKE_Fcst<-data.frame(forecast(NKE_Fcst, h=5))
PFE_Fcst<-data.frame(forecast(PFE_Fcst, h=5))
PG_Fcst<-data.frame(forecast(PG_Fcst, h=5))
T_Fcst<-data.frame(forecast(T_Fcst, h=5))
TRV_Fcst<-data.frame(forecast(TRV_Fcst, h=5))
UNH_Fcst<-data.frame(forecast(UNH_Fcst, h=5))
UTX_Fcst<-data.frame(forecast(UTX_Fcst, h=5))
V_Fcst<-data.frame(forecast(V_Fcst, h=5))
VZ_Fcst<-data.frame(forecast(VZ_Fcst, h=5))
WMT_Fcst<-data.frame(forecast(WMT_Fcst, h=5))
XOM_Fcst<-data.frame(forecast(XOM_Fcst, h=5))

#AXP_Fcst$Point.Forecast
#BA_Fcst$Point.Forecast

FCST<-rbind(AXP_Fcst$Point.Forecast, BA_Fcst$Point.Forecast)
FCST<-rbind(FCST, CAT_Fcst$Point.Forecast)
FCST<-rbind(FCST, CSCO_Fcst$Point.Forecast)
FCST<-rbind(FCST, CVX_Fcst$Point.Forecast)
FCST<-rbind(FCST, DD_Fcst$Point.Forecast)
FCST<-rbind(FCST, DIS_Fcst$Point.Forecast)
FCST<-rbind(FCST, GE_Fcst$Point.Forecast)
FCST<-rbind(FCST, GS_Fcst$Point.Forecast)
FCST<-rbind(FCST, HD_Fcst$Point.Forecast)
FCST<-rbind(FCST, IBM_Fcst$Point.Forecast)
FCST<-rbind(FCST, INTC_Fcst$Point.Forecast)
FCST<-rbind(FCST, JNJ_Fcst$Point.Forecast)
FCST<-rbind(FCST, JPM_Fcst$Point.Forecast)
FCST<-rbind(FCST, KO_Fcst$Point.Forecast)
FCST<-rbind(FCST, MCD_Fcst$Point.Forecast)
FCST<-rbind(FCST, MMM_Fcst$Point.Forecast)
FCST<-rbind(FCST, MRK_Fcst$Point.Forecast)
FCST<-rbind(FCST, MSFT_Fcst$Point.Forecast)
FCST<-rbind(FCST, NKE_Fcst$Point.Forecast)
FCST<-rbind(FCST, PFE_Fcst$Point.Forecast)
FCST<-rbind(FCST, PG_Fcst$Point.Forecast)
FCST<-rbind(FCST, T_Fcst$Point.Forecast)
FCST<-rbind(FCST, TRV_Fcst$Point.Forecast)
FCST<-rbind(FCST, UNH_Fcst$Point.Forecast)
FCST<-rbind(FCST, UTX_Fcst$Point.Forecast)
FCST<-rbind(FCST, V_Fcst$Point.Forecast)
FCST<-rbind(FCST, VZ_Fcst$Point.Forecast)
FCST<-rbind(FCST, WMT_Fcst$Point.Forecast)
FCST<-rbind(FCST, XOM_Fcst$Point.Forecast)

#Create the final forecast table
FCST<-data.frame(Stock=Stocks$Stocks, ARIMA=ARIMA$ARIMA, Time1=FCST[,1], Time2=FCST[,2], Time3=FCST[,3], Time4=FCST[,4], Time5=FCST[,5])

#
print(FCST, digits=4)
